name: hhjens-stack
services:
  app: 
    command: bash
    public: true
    image: okteto/node:12
    build: app
    replicas: 2
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi


